"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-28 17:49:06.385823
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector is created here so that Phase 1 can add embedding columns without a
    # privileged migration later; CREATE EXTENSION requires superuser.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('principal_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('retrieved_doc_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('denied_doc_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('answer_hash', sa.String(length=64), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_tenant_time', 'audit_log', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('source_uri', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.Text(), nullable=False),
    sa.Column('owner_group', sa.Text(), nullable=True),
    sa.Column('allowed_groups', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('need_to_know_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('min_clearance', sa.SmallInteger(), nullable=False),
    sa.Column('jurisdiction', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('acl_rule', sa.Text(), nullable=True),
    sa.Column('frontmatter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_document_sensitivity'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source', 'path', name='uq_document_path')
    )
    op.create_index('ix_documents_allowed_groups', 'documents', ['allowed_groups'], unique=False, postgresql_using='gin')
    op.create_index('ix_documents_content_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('ix_documents_tenant', 'documents', ['tenant_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effect', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('predicate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("effect IN ('allow', 'deny')", name='ck_policy_effect'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_policy_name')
    )
    op.create_table('principals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('groups', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('clearance', sa.SmallInteger(), nullable=False),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('employment_type', sa.Text(), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_id', name='uq_principal_external')
    )
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('heading_path', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('sensitivity', sa.Text(), nullable=False),
    sa.Column('allowed_groups', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('min_clearance', sa.SmallInteger(), nullable=False),
    sa.Column('acl_source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("acl_source IN ('inherited', 'override')", name='ck_chunk_acl_source'),
    sa.CheckConstraint("sensitivity IN ('public', 'internal', 'confidential', 'restricted')", name='ck_chunk_sensitivity'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'ordinal', name='uq_chunk_ordinal')
    )
    op.create_index('ix_chunks_allowed_groups', 'chunks', ['allowed_groups'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_document', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_tenant', 'chunks', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_tenant', table_name='chunks')
    op.drop_index('ix_chunks_document', table_name='chunks')
    op.drop_index('ix_chunks_allowed_groups', table_name='chunks', postgresql_using='gin')
    op.drop_table('chunks')
    op.drop_table('principals')
    op.drop_table('policies')
    op.drop_index('ix_documents_tenant', table_name='documents')
    op.drop_index('ix_documents_content_hash', table_name='documents')
    op.drop_index('ix_documents_allowed_groups', table_name='documents', postgresql_using='gin')
    op.drop_table('documents')
    op.drop_table('tenants')
    op.drop_index('ix_audit_tenant_time', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
