"""query cache keyed by entitlement, and the visibility epoch that retires it

The cache stores chunk *ids*, never chunk content: a hit re-fetches them through RLS, so
the cache can never become a second copy of the corpus living outside the access model.
See `gatekeeper.retrieval.cache` for why that is worth more than the milliseconds it costs.

`cache_epochs` is a row per bump rather than one mutable counter, so that when the hit rate
collapses you can tell a policy change apart from a reindex.

**Hand-written, not autogenerated, and that was not a stylistic choice.** Running
`alembic revision --autogenerate` here produced a migration that dropped
`ix_chunks_embedding_384_hnsw`, both partial HNSW graphs, `ix_chunks_need_to_know` and
`ix_chunks_injection_flagged` — every index in this project created by raw SQL, because
autogenerate compares against ORM metadata and those indexes are invisible to it. Applying
it would have silently removed the vector indexes and turned every query into a sequential
scan. Any future migration in this repo has to be written by hand or diffed with real care.

No vector index on `query_cache`: a lookup scans one entitlement bucket, which holds tens
of rows, and an HNSW graph over it would cost more to maintain than the scan costs to run.

Revision ID: 0010_query_cache
Revises: 0009_injection
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import HALFVEC
from sqlalchemy.dialects import postgresql

revision: str = "0010_query_cache"
down_revision: str | None = "0009_injection"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "cache_epochs",
        sa.Column("epoch", sa.Integer(), primary_key=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )

    op.create_table(
        "query_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("epoch", sa.Integer(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column(
            "chunk_ids",
            postgresql.ARRAY(postgresql.UUID(as_uuid=True)),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("embedding_384", HALFVEC(384), nullable=True),
        sa.Column("embedding_model", sa.Text(), nullable=False),
        sa.Column("hits", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index("ix_query_cache_fingerprint", "query_cache", ["fingerprint"])
    op.create_index("ix_query_cache_epoch", "query_cache", ["epoch"])

    # The cache holds no tenant data of its own -- chunk ids are meaningless without a
    # subsequent authorized fetch -- and it is read and written only by the admin plane.
    # It is therefore deliberately NOT under RLS, and the app role gets no access to it.
    op.execute("REVOKE ALL ON query_cache FROM gatekeeper_app")
    op.execute("REVOKE ALL ON cache_epochs FROM gatekeeper_app")


def downgrade() -> None:
    op.drop_index("ix_query_cache_epoch", table_name="query_cache")
    op.drop_index("ix_query_cache_fingerprint", table_name="query_cache")
    op.drop_table("query_cache")
    op.drop_table("cache_epochs")
